name: Update awesome list

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Awesome generator
        uses: simonecorsi/mawesome@latest
        with:
          api-token: ${{ secrets.API_TOKEN }}
          github-email: github-actions[bot]
          github-name: github-actions[bot]@users.noreply.github.com
          template-path: template/README.ejs
          output-filename: README.md
